### ISSUE TITLE
Splash Logo

### ISSUE THREAD

**Issue by ggnull35** [pimoroni/rp_usbdisplay#10]
Hello,

We got 10 units.
Displays have Robopeak init screen and DFrobot splash logo.
How we can change splah logo ?

**Comment by Gadgetoid** [comment]
Unfortunately there's nothing I can do about that from a driver perspective.

It would require some custom firmware or modification to the displays themselves, since the splash is built-in. The RoboPeak website seems to be down at the moment, but when it's back up you should peruse the links at the bottom of this page to see if it's possible: https://www.dfrobot.com/index.php?route=product/product&product_id=1062#.UqbKc5ETznk
