### ISSUE TITLE
Use?

### ISSUE THREAD

**Issue by GamerGrug** [pimoroni/rp_usbdisplay#22]
Hi all, I picked up one of these Robopeak displays and want to use it for ANY use..  I have set it up in raspberry pi bullseye as a second display (all I can see is an X when I move my mouse over from the HDMI display).  What can I do from here?  I am a fresh raspberry pi user...  Can I (for example) use this usb display as a photo frame?

**Comment by Gadgetoid** [comment]
It's been a long, long time since I tried to use one of these displays.

I definitely haven't tried on Bullseye- what as the setup process like, did you use the drivers from here?

IIRC they set up a framebuffer at /dev/fb1 so anything that can display to a framebuffer will work.

This includes SDL (if you poke it in just the right way) and stuff like "fbi" - http://manpages.ubuntu.com/manpages/bionic/man1/fbi.1.html

fbi can be set up to advance through a directory of images as a slideshow, so it might be what you're after.

You probably also want to configure your X session to *not* use the display, since it's easier to run fullscreen apps on a secondary display by driving it directly. I'm actually surprised that you can move a mouse cursor over to the screen at all! Things have clearly changed in the last 5 years.

**Comment by GamerGrug** [comment]
Hi Gadgetoid!

Thank you very much for the reply!  There seems to be so little info out
there on this display, especially from the manufacturer, that I wonder if
it is worth doing more on any project using it.  I managed to pick this up
as part of a bulk sale of pi's and accessories so wanted to make use of it
somehow.  My thoughts were:

   - A PiGRRL type game device.  This was my preferred option, but the
   frame buffer copy was too slow to be useful really, and the RGB colours
   were mixed.  I read this was an issue with some devices needing red and
   blue to be swapped around.  Do you know if that can be done somehow?  I
   still would not mind using frame buffer copy to get a game device out of
   this.
   - A display for my weather station.  This would require a web page to be
   displayed on it.
   - A photo frame, albeit a very small one!

It was very easy to get going in Bullseye, just put on an SD, and when
setup to the HDMI all fine, I installed the drivers, DKMS, and then copied
the dualdisplay conf to the recommended X11 location.

I'm ok to put this aside, but wouldn't mind using it somehow if I can.  If
you have time to help me I would really appreciate it!!

Thanks again!
Alex.
